-- 1. List members with their role, skill, gender and office
SELECT
  TM.FIRST_NAME || ' ' || TM.LAST_NAME AS FULL_NAME,
  TM.ROLE,
  S.SKILL_NAME,
  G.LABEL AS GENDER,
  O.LOCATION_NAME
FROM TEAM_MEMBERS TM
JOIN SKILLS S ON TM.SKILL_ID = S.SKILL_ID
JOIN GENDERS G ON TM.GENDER_ID = G.GENDER_ID
JOIN OFFICES O ON TM.OFFICE_ID = O.OFFICE_ID;

-- 2. Number of projects per domain
SELECT DOMAIN, COUNT(*) AS PROJECT_COUNT
FROM PROJECTS
GROUP BY DOMAIN;

-- 3. Average dataset size per project
SELECT
  P.PROJECT_NAME,
  AVG(D.SIZE_MB) AS AVG_DATASET_SIZE
FROM DATASETS D
JOIN PROJECTS P ON D.PROJECT_ID = P.PROJECT_ID
GROUP BY P.PROJECT_NAME;

-- 4. Members who lead projects
SELECT
  TM.FIRST_NAME || ' ' || TM.LAST_NAME AS LEADER,
  P.PROJECT_NAME
FROM TEAM_MEMBERS TM
JOIN PROJECTS P ON TM.MEMBER_ID = P.LEAD_ID;
