-- UPDATE: Promote a team member
UPDATE TEAM_MEMBERS
SET ROLE = 'Senior Data Scientist'
WHERE MEMBER_ID = 'MB001';

-- DELETE: Remove a dataset
DELETE FROM DATASETS
WHERE DATASET_ID = 'DST02';

-- Check orphaned projects (no dataset)
SELECT P.PROJECT_NAME
FROM PROJECTS P
LEFT JOIN DATASETS D ON P.PROJECT_ID = D.PROJECT_ID
WHERE D.DATASET_ID IS NULL;
