-- ALTER: Add a phone number column to TEAM_MEMBERS
ALTER TABLE TEAM_MEMBERS
ADD PHONE_NUMBER VARCHAR(20);

-- Update some members with phone numbers
UPDATE TEAM_MEMBERS
SET PHONE_NUMBER = '0049-15123456789'
WHERE MEMBER_ID = 'MB001';

UPDATE TEAM_MEMBERS
SET PHONE_NUMBER = '0049-15234567890'
WHERE MEMBER_ID = 'MB004';

-- Insert a new team member to support later queries
INSERT INTO TEAM_MEMBERS (
  MEMBER_ID, FIRST_NAME, LAST_NAME, EMAIL, AGE, GENDER_ID, JOIN_DATE, ROLE, SKILL_ID, OFFICE_ID, PHONE_NUMBER
) VALUES (
  'MB006', 'Rahul', 'Sharma', 'rahul.sharma@gmail.com', 26, 'M', DATE('2024-04-01'), 'Intern - Data Analytics', 'SKL003', 'OFF001', '0049-1511112233'
);

-- Insert a new project and dataset for MB006
INSERT INTO PROJECTS (
  PROJECT_ID, PROJECT_NAME, DOMAIN, START_DATE, LEAD_ID
) VALUES (
  'PRJ04', 'Internship Analytics Dashboard', 'Internal BI', DATE('2024-04-15'), 'MB006'
);

INSERT INTO DATASETS (
  DATASET_ID, DATASET_NAME, SIZE_MB, CREATED_DATE, PROJECT_ID
) VALUES (
  'DST04', 'Employee Feedback Data', 250, DATE('2024-04-20'), 'PRJ04'
);

-- TRUNCATE (Commented for safety; uncomment only if testing with fresh data)
-- TRUNCATE TABLE DATASETS IMMEDIATE;

-- CTE: List members and how many projects they lead (including 0)
WITH ProjectCount AS (
  SELECT
    TM.MEMBER_ID,
    TM.FIRST_NAME,
    TM.LAST_NAME,
    COUNT(P.PROJECT_ID) AS PROJECTS_LED
  FROM TEAM_MEMBERS TM
  LEFT JOIN PROJECTS P ON TM.MEMBER_ID = P.LEAD_ID
  GROUP BY TM.MEMBER_ID, TM.FIRST_NAME, TM.LAST_NAME
)
SELECT * FROM ProjectCount
ORDER BY PROJECTS_LED DESC;

-- Aggregation: Average age per skill category
SELECT
  S.SKILL_NAME,
  ROUND(AVG(TM.AGE), 1) AS AVG_AGE
FROM TEAM_MEMBERS TM
JOIN SKILLS S ON TM.SKILL_ID = S.SKILL_ID
GROUP BY S.SKILL_NAME
ORDER BY AVG_AGE;

-- Window Function: Rank members by age within each office
SELECT
  TM.FIRST_NAME,
  TM.LAST_NAME,
  O.LOCATION_NAME,
  TM.AGE,
  RANK() OVER (PARTITION BY O.OFFICE_ID ORDER BY TM.AGE DESC) AS AGE_RANK
FROM TEAM_MEMBERS TM
JOIN OFFICES O ON TM.OFFICE_ID = O.OFFICE_ID
ORDER BY O.LOCATION_NAME, AGE_RANK;

-- Join: Show dataset details with project and project lead's full name
SELECT
  D.DATASET_NAME,
  D.SIZE_MB,
  P.PROJECT_NAME,
  TM.FIRST_NAME || ' ' || TM.LAST_NAME AS PROJECT_LEAD
FROM DATASETS D
JOIN PROJECTS P ON D.PROJECT_ID = P.PROJECT_ID
JOIN TEAM_MEMBERS TM ON P.LEAD_ID = TM.MEMBER_ID
ORDER BY D.SIZE_MB DESC;
