-- 2. Project summary report with project lead and dataset count
SELECT
  P.PROJECT_ID AS "Project ID",
  P.PROJECT_NAME AS "Project Name",
  P.DOMAIN AS "Domain",
  P.START_DATE AS "Start Date",
  TM.FIRST_NAME || ' ' || TM.LAST_NAME AS "Project Lead",
  COUNT(D.DATASET_ID) AS "Datasets Linked"
FROM PROJECTS P
JOIN TEAM_MEMBERS TM ON P.LEAD_ID = TM.MEMBER_ID
LEFT JOIN DATASETS D ON P.PROJECT_ID = D.PROJECT_ID
GROUP BY P.PROJECT_ID, P.PROJECT_NAME, P.DOMAIN, P.START_DATE, TM.FIRST_NAME, TM.LAST_NAME
ORDER BY P.START_DATE;
